# This is a configuration file for goreleaser.
# Make sure to check the documentation at https://goreleaser.com

project_name: talebook

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: talebook
    ldflags:
      - -s -w
      - -X github.com/bookstairs/talebook/config.gitMajor={{ .Major }}
      - -X github.com/bookstairs/talebook/config.gitMinor={{ .Minor }}
      - -X github.com/bookstairs/talebook/config.gitPatch={{ .Patch }}
      - -X github.com/bookstairs/talebook/config.gitCommit={{ .Commit }}
      - -X github.com/bookstairs/talebook/config.gitTreeState=clean
      - -X github.com/bookstairs/talebook/config.buildDate={{ .Date }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - '386'
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: linux
        goarch: '386'
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: '386'

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^web:'

archives:
  - id: talebook
    builds:
      - talebook
    format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: "{{ incpatch .Version }}-next"
