## This is a sample configuration file for talebook

# The binding port for backend server.
port: 8000

# The working directory for talebook.
working-path: "."

# The calibre library directory.
library-path: "./library"

# This is used to encrypt the cookie.
encrypt-key: "some-key"

# Allowed request per seconds.
limit: 300

# The executable file calibredb for adding books.
calibredb: "/usr/bin/calibredb"

# The executable file ebook-convert for converting books.
convert: "/usr/bin/ebook-convert"

# The cache in memory for storing frequently accessed files, such as the book cover.
file-cache: 300

# Enable debug log and metrics monitor and anything else.
debug: false
